@startuml

View ..> ChatAPI
ChatAPI <|.. PollingChatAPI
ChatAPI <|.. WebSocketChatAPI
ChatAPI <|.. GraphQLChatAPI

interface ChatAPI {
  sendMessage(message: string): void
  onMessage(listener: (message: string) => void): void
}

@enduml
